name: List Changed Folders

on:
  pull_request:
    branches:
      - main

jobs:
  list-folders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/git-diff@v4
        id: diff
        with:
          base: main
      - name: List changed folders and subfolders
        run: |
          echo "Changed folders and subfolders:"
          for file in ${{ steps.diff.outputs.modified_files }}; do
            echo "$(dirname $file)"
          done
