name: List Changed Folders

on:
  pull_request:
    types: [opened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List changed folders
        run: |
          git diff --name-only main | while read -r file; do
            echo "$(dirname "$file")"
          done | sort -u
