name: Folder Structure Changes

on:
  push:
    branches:
      - 'sub-branch'

jobs:
  folder_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List folder changes
        id: folder_changes
        run: |
          git fetch --depth=1 origin main
          CHANGED_FOLDERS=$(git diff --name-only main...$GITHUB_SHA | grep '/' | cut -d'/' -f1 | sort -u)
          echo "::set-output name=changed_folders::$CHANGED_FOLDERS"

      - name: Display changes
        run: echo "Changed folders: ${{ steps.folder_changes.outputs.changed_folders }}"
