name: Print Folder and Subfolder Name

on:
  push:
    paths:
      - '*/**' # Triggers on any changes within subfolders

jobs:
  print-folder-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Folder Structure
        run: |
          for d in */**/; do
            echo "Folder Name: $d"
            find "$d" -type f -name "changelog.xml" -exec dirname {} \;
          done
